### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by ffelten** [IDEALLab/EngiBench#4]
See also: https://docs.google.com/spreadsheets/d/1a_5sSs9tZFkxrVoueIog5beQjmxCcm8A/edit?usp=sharing&ouid=102104244358466653476&rtpof=true&sd=true

## Guidelines
- Easy, clean API: All the simulator-related details should be hidden from the users
- Safe bounds for simulation: some inputs will just crash the simulators, we should try to prevent that #29 
- Compatible with existing ML (Torch, TF, ...) and opti (surrogates) libraries: rely on HF datasets, provide compatibility layers
- Runnable anywhere: heavily rely on containers "pip install and run"
- Well documented: Pydoc, website are thoroughly documented
- Env versioning: whenever we break something or fix a bug that will alter the performance of the algos, we bump the version
- Rendering: each problem has a way to easily visualize a given design

## Problems and Features
- [x] Different fidelity of problems: hard and toys
- [x] Different physics: CFD, electronics, etc.
- [x] Constrained and unconstrained #29 
- [x] Different representations: point clouds, images, graphs
- [x] Multi-objective and single-objective
- [x] Different classes: topology, shape, parameterization, etc.
- [ ] Transform wrappers: some ways to convert between different design spaces e.g. vector to image #13 
- [x] Tutorials: in https://github.com/IDEALLab/EngiOpt and Collab notebooks

## Algos and Metrics
https://github.com/IDEALLab/EngiOpt
- [x] Different algos for different representations: 1d, 2d, etc.
- [x] Different vanilla algos: diffusion, VAE, GAN
- [x] Some tuned algos: BezierGANs, etc. #52 
- [x] Integrate with weights and biases: store checkpoints, training data, hyperparams, etc.
- [x] Different metrics, computed automagically when training? #27
