### ISSUE TITLE
Power Electronics TODO list

### ISSUE THREAD

**Issue by liangXD523** [IDEALLab/EngiBench#9]
- [ ] Fix `ruff: noqa` for `power_electronics.py` and `rawread.py`.
- [x] Remove args of `__init__(self)`. Add a `load(original_netlist_path, bucket_id)` method instead.
- [x] Add `dataset`.
- [x] Compute the variable size `design_space` with types such as float and binary.
- [ ] README.
- [x] Complete docstrings.
